- name: Test Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Hello world
      ansible.builtin.debug:
        msg: "Hello Demo!"
    - name: sleep
      ansible.builtin.pause:
        seconds: 60
